spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password:
      jdbc-url: jdbc:h2:file:~/example-db
  thymeleaf:
    cache: false

demo:
  users:
    - username: admin
      password: admin
      roles:
        - ADMIN